#!/usr/bin/env bash
# Will display information about subdomains

displayDomain() {

	domain="$1"
	subdomain="$2"

	echo $domain
	echo $subdomain

	subdomainInfo=$(dig "www.mikerock.tech" | grep -A1 "ANSWER SECTION:")

	echo "Info: $subdomainInfo"
	domainName=$(echo "$subdomainInfo" | grep -Eo "\w[^A-Z :].*.[a-z]")
	echo "DNS: $domainName"
	subdomainName=$(echo "$domainName" | grep -Eo "^[^.]*")
	echo "Subdomain: $subdomainName"
	destIP=$(echo "$subdomainInfo" | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}")
	echo "IP $destIP"
}
