#!/usr/bin/env bash
# Will display information about subdomains

displayDomain() {

	domain="$1"
	subdomain="$2"

	if [ -z "$subdomain" ]
	then
		echo "No subdomain"
	else
		subdomainInfo=$(dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION:")
	fi

	domainName=$(echo "$subdomainInfo" | grep -Eo "\w[^A-Z :].*.[a-z]")
	subdomainName=$(echo "$domainName" | grep -Eo "^[^.]*")
	destIP=$(echo "$subdomainInfo" | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}")
	recordType=$(echo "$subdomainInfo" | awk '{ printf $4}')

	echo "The subdomain $subdomainName is a $recordType record and points to $destIP"
}
