#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MikeRock51 permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-available/default
sudo systemctl restart nginx
