#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.


sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/MikeRock51 permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
replace404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t root \/usr\/share\/nginx\/html;\n\t internal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace404/" /etc/nginx/sites-enabled/default

sudo service nginx restart
