#!/bin/bash
# Install and configure HAproxy on a server

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.7 -y
sudo apt-get install haproxy=2.7.\* -y

replace="errorfile 408 \/etc\/haproxy\/errors\/408.http\n\nlisten http\n\tbind *:80\n\tbalance roundrobin\n\tserver 151482-web-01 54.237.86.166:80 check\n\tserver 151482-web-02 54.236.48.218:80 check"
sudo sed -i "s/errorfile 408 \/etc\/haproxy\/errors\/408.http/$replace/" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
