#!/bin/bash
# Install and configure HAproxy on a server

sudo apt update
sudo apt install haproxy -y

sudo echo "
listen http
	bind *:80
	balance roundrobin
	server 151482-web-01 54.237.86.166:80 check
	server 151482-web-02 54.236.48.218:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
