#!/bin/bash
# Install and configure HAproxy on a server

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.7 -y
sudo apt-get install haproxy=2.7.\* -y

sudo echo "
listen http
	bind *:80
	balance roundrobin
	server 151482-web-01 54.237.86.166:80 check
	server 151482-web-02 54.236.48.218:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
