#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p"$1" --all-databases --master-data > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
