#!/usr/bin/env bash
# A Bash script that displays To infinity and beyond indefinitely whyile resisting termination

while true
do
	trap 'echo "I am invincible!!!"' TERM
	echo "To infinity and beyond"
	sleep 2
done