#!/usr/bin/env bash
# A script that prints "Best School" 10 times using a while loop + "Hi" at the 9th iteration

var=0;
while ((var<10))
do
	echo "Best School"
	if ((var==8))
	then
		echo "Hi"
	fi
	((var++))
done
