#!/usr/bin/env bash
# Displays the content of the current directory in a list format

cwd=$(ls)
for file in $cwd
	do
		if [[ $file == .* ]]; then
			continue
		fi
		file_name_parts=$(echo "$file" | cut -d '-' -f 2-)
		echo "${file_name_parts}"
	done
