#!/usr/bin/env bash
# Share your SSH client configuration in your answer file.
    # Requirements:
        # Your SSH client configuration must be configured to use the private key ~/.ssh/school
        # Your SSH client configuration must be configured to refuse to authenticate using a password

Host 18.209.224.255
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
